name: CI - Build and Test ASP.NET 8

on:
  push:
    branches: [ "master" ]  # hoặc "master" nếu bạn dùng master
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: 📥 Checkout source
      uses: actions/checkout@v4

    - name: 🛠️ Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: 🔄 Restore dependencies
      run: dotnet restore

    - name: 🧱 Build
      run: dotnet build --no-restore

    - name: ✅ Test
      run: dotnet test --no-build --verbosity normal
